import Head from "next/head";
import process from "process";
import { make } from "@/util/make";
import React, { useState } from "react";
import "bootstrap-icons/font/bootstrap-icons.scss";
import styles from "@/styles/modules/Home.module.scss";
import { Login } from "@/components/login";

function createSocket() {
    /** @type {WebSocket} */
    let ws;
    try {
        const url = process.env("WS_URL").toString();
        console.log(url);
        ws = new WebSocket(url);
    } catch (err) {
        console.error(err);
        return;
    }
    
    return ws;
}

let message = React.createRef();
let nickname = React.createRef();
let exceptMessage = React.createRef();

export default function Home() {
    const [login, setLogin] = useState(false);
    const [messages, setMessages] = useState([]);

    let socket;
    try {
        socket = new createSocket();
    } catch (err) {
        console.error(err);
        return;
    }
    
    socket.onmessage = (event) => {
        setMessages(prev => [...prev, event.data]);
    };

    return (
        <>
            <Head>
                <title>Personal IRC Simple Chat</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                {login ? "Hello!" : <Login socket={socket} login={login} setLogin={setLogin}/>}
            </main>
        </>
    );
}
